# Generated by Django 3.2.8 on 2021-10-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(blank='true', max_length=50, null='true')),
                ('city', models.CharField(blank='true', max_length=50, null='true')),
                ('state', models.CharField(blank='true', max_length=50, null='true')),
                ('postal_code', models.CharField(blank='true', max_length=50, null='true')),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
            },
        ),
    ]
