# Generated by Django 3.2.8 on 2021-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarybooks', '0002_book_library_activity_library_book_library_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='library_book',
            name='activity_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Last activity ID'),
        ),
    ]
